
PROG = pf_serial

CFLAGS = -DPF_SLAVE
CXXFLAGS += -std=c++14
CXXFILES = pf_serial.cpp
HEADERS = sort_adapter.h include_tuw_slmaster/com_structs.h include_tuw_slmaster/fixedpoint.h include_tuw_slmaster/config.h

LIBS += -lulx2s

#WITHOUT_FLOAT = false

include ${POST_MK}
# DO NOT DELETE
