
PROG = ustl_test

CXXFLAGS += -std=c++14 -I"./ustl-2.3" -Werror=varargs

CFILES = strdup.c calloc.c
CXXFILES = ustl_test.cpp ustl-2.3/memblock.cc ustl-2.3/cmemlink.cc ustl-2.3/ustring.cc ustl-2.3/unew.cc ustl-2.3/ualgobase.cc

#LIBS += -lulx2s

#WITHOUT_FLOAT = false

include ${POST_MK}
# DO NOT DELETE
